### ISSUE TITLE
It gives me an error saying that it doesn't know what to put in the theme colour and I can't seem to find the problem

### ISSUE THREAD

**Issue by New-khaled** [matheusfelipeog/calculadora-tk#24]
im on Mac this the error
Traceback (most recent call last):
  File "/Users/mahmoudhadef/Downloads/calculadora-tk-master/main.py", line 14, in <module>
    main = Calculadora(master)
  File "/Users/mahmoudhadef/Downloads/calculadora-tk-master/app/calculadora.py", line 69, in __init__
    self._create_input(self._frame_input)
  File "/Users/mahmoudhadef/Downloads/calculadora-tk-master/app/calculadora.py", line 95, in _create_input
    self._entrada = tk.Entry(master, cnf=self.theme['INPUT'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 3064, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 2601, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name ""

**Comment by KATTASAHAN** [comment]
Sorry i didn't get the issue
could you help me with some screen shorts or more elaborated explanation?
